apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-bridge
  namespace: iot-monitoring
  labels:
    app: mqtt-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-bridge
  template:
    metadata:
      labels:
        app: mqtt-bridge
    spec:
      containers:
        - name: mqtt-bridge
          image: your-registry/aws-iot-mqtt-bridge:latest # Replace with your image
          imagePullPolicy: Always
          env:
            - name: AWS_IOT_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: aws-iot-secrets
                  key: endpoint
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-iot-credentials
                  key: aws-region
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: timescaledb-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: timescaledb-credentials
                  key: password
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
            - name: certs-volume
              mountPath: /app/certs
      volumes:
        - name: config-volume
          configMap:
            name: mqtt-bridge-config
        - name: certs-volume
          secret:
            secretName: aws-iot-credentials
            items:
              - key: iot-certificate.pem.crt
                path: iot-certificate.pem.crt
              - key: iot-private.pem.key
                path: iot-private.pem.key
              - key: root-CA.crt
                path: root-CA.crt
