# mqtt-bridge/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-bridge
  namespace: iot-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-bridge
  template:
    metadata:
      labels:
        app: mqtt-bridge
    spec:
      containers:
        - name: mqtt-bridge
          image: mqtt-bridge:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: aws-iot-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aws-iot-credentials
                  key: password
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
            - name: certs-volume
              mountPath: /app/certs
      volumes:
        - name: config-volume
          configMap:
            name: mqtt-bridge-config
        - name: certs-volume
          secret:
            secretName: aws-iot-credentials
            items:
              - key: certificate.pem.crt
                path: certificate.pem.crt
              - key: private.pem.key
                path: private.pem.key
              - key: root-ca.crt
                path: root-ca.crt
              - key: username
                path: username
              - key: password
                path: password
