apiVersion: v1
kind: Service
metadata:
  name: mqtt-bridge
  namespace: iot-monitoring
spec:
  selector:
    app: mqtt-bridge
  ports:
    - port: 8883
      targetPort: 8883
      protocol: TCP
      name: mqtt-secure
  type: ClusterIP
