apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgis
  namespace: iot-monitoring
  labels:
    app: postgis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgis
  strategy:
    type: Recreate # Ensures the pod is fully terminated before creating a new one
  template:
    metadata:
      labels:
        app: postgis
    spec:
      containers:
        - name: postgis
          image: postgis/postgis:15-3.3 # Using PostgreSQL 15 with PostGIS 3.3
          env:
            - name: POSTGRES_PASSWORD
              value: "postgres" # In production, use a Secret instead
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_DB
              value: "postgres"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          ports:
            - containerPort: 5432
              name: postgis
          volumeMounts:
            - name: postgis-data
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
      volumes:
        - name: postgis-data
          persistentVolumeClaim:
            claimName: postgis-data
        - name: init-scripts
          configMap:
            name: postgis-init-scripts
