apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgis-data
  namespace: iot-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path # Using the same storage class as before
