apiVersion: v1
kind: Service
metadata:
  name: postgis
  namespace: iot-monitoring
  labels:
    app: postgis
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgis
  selector:
    app: postgis
  type: ClusterIP # Only accessible within the cluster
