apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
  namespace: iot-monitoring
  labels:
    app: timescaledb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
        - name: timescaledb
          image: timescale/timescaledb:latest-pg14
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: "timescaledbpassword" # change to use secret or env
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_DB
              value: "sensor_data"
          volumeMounts:
            - name: timescaledb-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: timescaledb-data
          persistentVolumeClaim:
            claimName: timescaledb-data
        - name: init-script
          configMap:
            name: timescaledb-init
