apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescaledb-data
  namespace: iot-monitoring
spec:
  accessModes:
    - ReadWriteOnce # Can be mounted as read-write by a single node
  resources:
    requests:
      storage: 5Gi # Request 5GB of storage
  # K3s uses local-path as the default storage class
  # No need to specify storageClassName unless you want a different one
