apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  namespace: iot-monitoring
  labels:
    app: timescaledb
spec:
  selector:
    app: timescaledb
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  type: ClusterIP
